apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-world
spec:
  destination:
    name: ''
    namespace: my-app1
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/thangap-cloud/k8s-local-cd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

